### PR TITLE
add appropriate qualifiers (constexpr, const, override)

### PR DESCRIPTION
**Pull request by hiroki-kojima**

### CODE REVIEW

**Comment by hiroki-kojima** [comment]
@diegodox 
The conflict has been resolved.

**Comment by diegodox** [comment]
@hiroki-kojima 
> The conflict has been resolved.
thank you.

LGTM

**Comment by diegodox** [comment]
@hiroki-kojima  how about these comment ☝🏻 ?

**Comment by hiroki-kojima** [comment]
@diegodox 
LGTM

**Pull request merged**
